language: python

python:
  - '3.6'

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/eggs

install:
  - pip install -r requirements.txt
  - buildout

script:
  - isort `find src/mr.roboto/ -name "*.py"`
  - black -S --py36 src/mr.roboto/
  - bin/code-analysis
  - bin/pytest --cov=src/mr.roboto --cov-report term-missing src/mr.roboto/

after_success:
  - pip install -q coveralls
  - coveralls
